package bloodbank;


import static bloodbank.BloodBank.con;
import bloodbank.HomePage;
import bloodbank.UserStaff;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class StaffDetails extends javax.swing.JFrame {

    /**
     * Creates new form StaffDetails
     */
    public StaffDetails() {
        initComponents();
        showUserStaff();
    }
    
    public ArrayList<UserStaff>userStaffList(){
            ArrayList<UserStaff>userStaffList = new ArrayList<> ();
            
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=BLOOD_BANK_MANAGEMENT_SYSTEM;user=sa;password=samithasan";
        
                Connection connection = DriverManager.getConnection(url);
                String queryS = "SELECT * FROM Staff";
                Statement st = connection.createStatement();
                ResultSet rs = st.executeQuery(queryS);
                UserStaff userstaff;
              
                while(rs.next()){
                    userstaff = new UserStaff(rs.getInt("staff_ID"), rs.getString("staff_Name"), rs.getString("staff_phNo"), rs.getInt("staff_salary"));
                    userStaffList.add(userstaff);
                }

                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
            return userStaffList;
        }
    public void showUserStaff(){
        ArrayList<UserStaff> list = userStaffList();
        DefaultTableModel model= (DefaultTableModel) staff_table.getModel();
        Object[] row = new Object[4];
        for(int i=0; i<list.size(); i++){
            row[0]=list.get(i).getstaff_ID();
            row[1]=list.get(i).getstaff_Name();
            row[2]=list.get(i).getstaff_phNo();
            row[3]=list.get(i).getstaff_salary();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_sum = new javax.swing.JTextField();
        avgSalary = new javax.swing.JButton();
        txt_avg = new javax.swing.JTextField();
        btn_seach = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 32)); // NOI18N
        jLabel2.setText("All Staff Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 30, 360, 38);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 80, 990, 10);

        staff_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Staff Name", "Staff Phone No", "Staff Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(staff_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 560, 370);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Back to Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 20, 170, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 0));
        jButton2.setText("Total Salary");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 170, 150, 40);

        txt_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sumActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sum);
        txt_sum.setBounds(850, 170, 130, 40);

        avgSalary.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        avgSalary.setForeground(new java.awt.Color(255, 0, 0));
        avgSalary.setText("Average Salary");
        avgSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(avgSalary);
        avgSalary.setBounds(670, 230, 150, 40);

        txt_avg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avgActionPerformed(evt);
            }
        });
        jPanel1.add(txt_avg);
        txt_avg.setBounds(850, 230, 130, 40);

        btn_seach.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_seach.setForeground(new java.awt.Color(0, 153, 51));
        btn_seach.setText("Search Staff");
        btn_seach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seachActionPerformed(evt);
            }
        });
        jPanel1.add(btn_seach);
        btn_seach.setBounds(810, 20, 200, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 0));
        jButton3.setText("Staffs whose salary is greater than average salary");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(620, 340, 410, 60);

        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 51, 0));
        btn_delete.setText("Delete Row");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(620, 440, 410, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DDForm.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1059, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;databaseName=BLOOD_BANK_MANAGEMENT_SYSTEM;user=sa;password=samithasan";
        
        con = DriverManager.getConnection(url);
            
          
            //String query="";
           
          String query="SELECT SUM(staff_salary) 'SUM(staff_salary)' FROM Staff ";
            
          
            
             
           // System.out.println(query);
            PreparedStatement pst=con.prepareStatement(query);
        //pst.setString(1, textFieldSearch.getText());
         ResultSet rs=pst.executeQuery();
         
         if(rs.next()){
         String sum=rs.getString("SUM(staff_salary)");
         txt_sum.setText(sum);
         }
         
          /* while(rs.next()) 
               String s[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
              model.addRow(s);
           }*/
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sumActionPerformed

    private void avgSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgSalaryActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;databaseName=BLOOD_BANK_MANAGEMENT_SYSTEM;user=sa;password=samithasan";
        
        con = DriverManager.getConnection(url);
            
          
            //String query="";
           
          String query="SELECT AVG(staff_salary) 'AVG(staff_salary)' FROM Staff ";
            
          
            
             
           // System.out.println(query);
            PreparedStatement pst=con.prepareStatement(query);
        //pst.setString(1, textFieldSearch.getText());
         ResultSet rs=pst.executeQuery();
         
         if(rs.next()){
         String sum=rs.getString("AVG(staff_salary)");
         txt_avg.setText(sum);
         }
         
          /* while(rs.next()) 
               String s[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
              model.addRow(s);
           }*/
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_avgSalaryActionPerformed

    private void txt_avgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avgActionPerformed

    private void btn_seachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seachActionPerformed
        // TODO add your handling code here:
        SearchStaff ss = new SearchStaff();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_seachActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) staff_table.getModel();
          model.setRowCount(0);
        
         try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;databaseName=BLOOD_BANK_MANAGEMENT_SYSTEM;user=sa;password=samithasan";
        
        con = DriverManager.getConnection(url);
            
          
            String query="";
           
            query="SELECT * FROM Staff where staff_salary>(SELECT AVG(staff_salary) FROM Staff)";
            
            
            System.out.println(query);
            PreparedStatement pst=con.prepareStatement(query);
        //    pst.setString(1, textFieldSearch.getText());
            ResultSet rs=pst.executeQuery();
           while(rs.next()) {
               String s[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
              model.addRow(s);
           }
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;databaseName=BLOOD_BANK_MANAGEMENT_SYSTEM;user=sa;password=samithasan";
        
        con = DriverManager.getConnection(url);
        int row =staff_table.getSelectedRow();
        String value = (staff_table.getModel().getValueAt(row, 0).toString());
        String query1 = "DELETE FROM Staff where staff_ID="+value;
        PreparedStatement pst = con.prepareStatement(query1);
        pst.executeUpdate();
        DefaultTableModel model = (DefaultTableModel)staff_table.getModel();
        model.setRowCount(0);
        
    showUserStaff();
        JOptionPane.showMessageDialog(null,"Deleted Successfully");
        
         }
         catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);        
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avgSalary;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_seach;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable staff_table;
    private javax.swing.JTextField txt_avg;
    private javax.swing.JTextField txt_sum;
    // End of variables declaration//GEN-END:variables
}
